InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('(theme)=>theme === "light" ? "dark" : "light"') contains HTML space characters, which are not valid in tokens.     at https://6000-idx-studio-1745662480131.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/_0af4821b._.js:268:73     at https://6000-idx-studio-1745662480131.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/_0af4821b._.js:300:9     at $ (https://6000-idx-studio-1745662480131.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/_0af4821b._.js:259:766)     at ThemeProvider (https://6000-idx-studio-1745662480131.cluster-jbb3mjctu5cbgsi6hwq6u4btwe.cloudworkstations.dev/_next/static/chunks/_0af4821b._.js:17:214)     at RootLayout (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__bb51b579._.js?0:131:274)